sudo: required
language: node_js

os:
  - linux-ppc64le
  - linux

cache:
  apt: true
  directories:
    - "$TRAVIS_CACHE_DIR"

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

services:
  - docker

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - make init
  - make log:init
  - source travis-env.sh
  - make docker-login
  - chmod +x copyright-check.sh

install:
  - make install

before_script:
  - make test

script:
  - make copyright-check
  - make image

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" && make release || echo  "success"
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
            echo "All jobs succeeded! Creating multi arch image..."
            make manifest-tool
            make multi-arch
          else
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi
  - make log:pass

after_failure: 
  - make log:fail
